{
    "name": "charity-connect-backend",
    "env": "node",
    "buildCommand": "npm install",
    "startCommand": "node server.js",
    "healthCheckPath": "/health",
    "envVars": [
        {
            "key": "NODE_ENV",
            "value": "production"
        }
    ]
}
